version: "3.8"
networks:
    laravel:
        driver: bridge

services:
    app:
        build:
            args:
                user: laravel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel
        ports:
            - 5173:5173
        container_name: laravel-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel
    mysql:
        container_name: laravel-mysql
        image: mysql:latest
        command: mysqld --sql_mode=""
        networks:
            - laravel
        ports:
            - "33306:3306"
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
    mysql-test:
        container_name: laravel-mysql-test
        image: mysql:latest
        command: mysqld --sql_mode=""
        networks:
            - laravel
        volumes:
            - mysql_testing:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel-test
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel-test
            MYSQL_PASSWORD: secret-test
    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravel

volumes:
    mysql:
    mysql_testing:
